main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import api, difflist, difflist_level_select, edit, index, level, level_select, omikuji, ranking, \
    ranking_detail, ranking_level_select, search

app_name = 'main'
urlpatterns = [
    path('', index.index, name='index'),
    path('search/', search.search, name='search'),
    path('level/', level_select.level_select, name='level_select'),
    path('level/<int:level>/', level.level, name='level'),
    path('difflist/', difflist_level_select.difflist_level_select, name='difflist_level_select'),
    path('difflist/<int:sran_level>/', difflist.difflist, name='difflist'),
    path('edit/<int:music_id>/', edit.edit, name='edit'),
    path('ranking/', ranking_level_select.ranking_level_select, name='ranking_level_select'),
    path('ranking/<int:sran_level>/', ranking.ranking, name='ranking'),
    path('ranking/detail/<int:music_id>/', ranking_detail.ranking_detail, name='ranking_detail'),
    path('omikuji/', omikuji.omikuji, name='omikuji'),
    path('premium/', TemplateView.as_view(template_name="main/premium.html"), name='premium'),
    path('api/get_clear_status/<int:music_id>/', api.get_clear_status, name='get_clear_status'),
    path('api/get_bad_count/<int:music_id>/', api.get_bad_count, name='get_bad_count'),
    path('api/get_medal/<int:music_id>/', api.get_medal, name='get_medal'),
    path('api/get_latest_updated_at/<int:music_id>/', api.get_latest_updated_at, name='get_latest_updated_at'),
    path('api/get_bad_count_avg/<int:music_id>/', api.get_bad_count_avg, name='get_bad_count_avg'),
    path('api/get_myrank/<int:music_id>/', api.get_myrank, name='get_myrank'),
    path('api/get_medal_count/<int:music_id>/', api.get_medal_count, name='get_medal_count'),
    path('api/get_folder_lamp/<int:level>/', api.get_folder_lamp, name='get_folder_lamp'),
]

srandom/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('main.urls')),
    path('mastermind/', admin.site.urls),
    path('maintenance-mode/', include('maintenance_mode.urls')),
    path('auth/', include(('django.contrib.auth.urls', 'auth'))),
    path('social/', include(('social_django.urls', 'social'))),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    import debug_toolbar
    # ref. https://docs.djangoproject.com/ja/4.1/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + staticfiles_urlpatterns()

users/urls.py
from django.urls import path

from .views import api, cleardata, deactivate, download, list, mypage, settings, statistics

app_name = 'users'
urlpatterns = [
    path('list/', list.list_users, name='list'),
    path('settings/', settings.settings, name='settings'),
    path('deactivate/', deactivate.deactivate, name='deactivate'),
    path('<username>/', mypage.mypage, name='mypage'),
    path('<username>/statistics/', statistics.statistics, name='statistics'),
    path('<username>/cleardata/<int:sran_level>/', cleardata.cleardata, name='cleardata'),
    path('download/<file_type>/', download.download, name='download'),
    path('api/get_percentage_of_clear/<int:user_id>/', api.get_percentage_of_clear, name='get_percentage_of_clear'),
    path('api/get_activity_map/', api.get_activity_map, name='get_activity_map'),
    path('api/get_clear_rate/', api.get_clear_rate, name='get_clear_rate'),
]

users/views/api.py
import json
from datetime import datetime
from zoneinfo import ZoneInfo

from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_GET

from main.models import Activity, Extra_Option, Medal, Music, Sran_Level

from users.models import CustomUser


@require_GET
def get_percentage_of_clear(request: HttpRequest, user_id: int) -> JsonResponse:
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'Invalid access'}, status=400)

    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user and (not user.is_active or user.cleardata_privacy == 2):
        raise PermissionDenied

    max_s_lv = Sran_Level.MAX
    music_num = [0] * max_s_lv
    clear_num = [0] * max_s_lv
    percentage_of_clear = [0] * max_s_lv

    for s_lv in range(1, max_s_lv + 1):
        i = s_lv - 1
        music_list = Music.objects.filter(sran_level=s_lv)
        music_num[i] = music_list.count()

        medals = Medal.objects.filter(user=user, music__in=music_list, medal__lte=7)
        clear_num[i] = medals.count()

        # クリア率を計算
        if music_num[i] > 0:
            percentage_of_clear[i] = round((clear_num[i] / music_num[i]) * 100)

    context = {
        'percentage_of_clear': percentage_of_clear,
        'music_num': music_num,
        'clear_num': clear_num
    }

    return JsonResponse(context)


@require_GET
def get_activity_map(request: HttpRequest) -> HttpResponse:
    if ('user_id' not in request.GET) or ('start' not in request.GET) or ('stop' not in request.GET):
        raise Http404()

    user_id = request.GET['user_id']
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user:
        if not user.is_active or user.cleardata_privacy == 2:
            raise PermissionDenied

    start = int(request.GET['start'])
    end = int(request.GET['stop'])

    start_datetime = datetime.fromtimestamp(start / 1000.0, tz=ZoneInfo('Asia/Tokyo'))
    end_datetime = datetime.fromtimestamp(end / 1000.0, tz=ZoneInfo('Asia/Tokyo'))

    activities = Activity.objects.filter(user=user_id, updated_at__range=(start_datetime, end_datetime))
    result = {}
    for activity in activities:
        updated_at = str(int(datetime.timestamp(activity.updated_at)))
        if updated_at in result:
            result[updated_at] += 1
        else:
            result.update({updated_at: 1})

    json_str = json.dumps(result, ensure_ascii=False)
    return HttpResponse(json_str, content_type='application/json; charset=UTF-8')


@require_GET
def get_clear_rate(request: HttpRequest) -> HttpResponse:
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'Invalid access'}, status=400)

    if 'user_id' not in request.GET:
        raise Http404()

    user_id = request.GET['user_id']
    user = get_object_or_404(CustomUser, pk=user_id)

    max_s_lv = Sran_Level.MAX
    s_lv_range = range(max_s_lv, Sran_Level.MIN - 1, -1)

    chart_data = {
        'clearRate': {
            'labels': [],
            'datasets': [{
                'label': 'Perfect',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1
            }, {
                'label': 'Full Combo',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1
            }, {
                'label': 'Hard Clear',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1
            }, {
                'label': 'Clear',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1
            }, {
                'label': 'Easy Clear',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1
            }, {
                'label': 'Failed',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 1,
            }, {
                'label': 'No Play',
                'data': [],
                'backgroundColor': [],
                'borderWidth': 0
            }]
        }
    }

    # clearRate
    music_num = [0] * max_s_lv
    medal_num = {
        'perfect': [0] * max_s_lv,
        'fullcombo': [0] * max_s_lv,
        'hard': [0] * max_s_lv,
        'clear': [0] * max_s_lv,
        'easy': [0] * max_s_lv,
        'failed': [0] * max_s_lv,
        'no-play': [0] * max_s_lv
    }
    percentage_of_medals = {
        'perfect': [0] * max_s_lv,
        'fullcombo': [0] * max_s_lv,
        'hard': [0] * max_s_lv,
        'clear': [0] * max_s_lv,
        'easy': [0] * max_s_lv,
        'failed': [0] * max_s_lv
    }
    for s_lv in s_lv_range:
        i = s_lv - 1
        music_list = Music.objects.filter(sran_level=s_lv)
        music_num[i] = len(music_list)
        for music in music_list:
            try:
                medal = Medal.objects.get(user=user, music=music)
                if medal.medal == 1:
                    medal_num['perfect'][i] += 1
                elif 2 <= medal.medal <= 4:
                    medal_num['fullcombo'][i] += 1
                elif 5 <= medal.medal <= 7:
                    try:
                        extra_option = Extra_Option.objects.get(user=user, music=music)
                        if extra_option.hard:
                            medal_num['hard'][i] += 1
                        else:
                            medal_num['clear'][i] += 1
                    except ObjectDoesNotExist:
                        medal_num['clear'][i] += 1
                elif medal.medal == 11:
                    medal_num['easy'][i] += 1
                elif 8 <= medal.medal <= 10:
                    medal_num['failed'][i] += 1
                else:
                    medal_num['no-play'][i] += 1
            except ObjectDoesNotExist:
                medal_num['no-play'][i] += 1

        # 各レベルのメダルの割合を計算
        percentage_of_medals['perfect'][i] = round(medal_num['perfect'][i] * 100 / music_num[i])
        percentage_of_medals['fullcombo'][i] = round(
            medal_num['fullcombo'][i] * 100 / music_num[i])
        percentage_of_medals['hard'][i] = round(medal_num['hard'][i] * 100 / music_num[i])
        percentage_of_medals['clear'][i] = round(medal_num['clear'][i] * 100 / music_num[i])
        percentage_of_medals['easy'][i] = round(medal_num['easy'][i] * 100 / music_num[i])
        percentage_of_medals['failed'][i] = round(medal_num['failed'][i] * 100 / music_num[i])

        chart_data['clearRate']['labels'].append("Lv" + str(s_lv))

        chart_data['clearRate']['datasets'][0]['data'].append(percentage_of_medals['perfect'][i])
        chart_data['clearRate']['datasets'][1]['data'].append(percentage_of_medals['fullcombo'][i])
        chart_data['clearRate']['datasets'][2]['data'].append(percentage_of_medals['hard'][i])
        chart_data['clearRate']['datasets'][3]['data'].append(percentage_of_medals['clear'][i])
        chart_data['clearRate']['datasets'][4]['data'].append(percentage_of_medals['easy'][i])
        chart_data['clearRate']['datasets'][5]['data'].append(percentage_of_medals['failed'][i])

        chart_data['clearRate']['datasets'][0]['backgroundColor'].append('#4a4a4a')
        chart_data['clearRate']['datasets'][1]['backgroundColor'].append('rgb(153, 207, 229)')
        chart_data['clearRate']['datasets'][2]['backgroundColor'].append('rgb(243, 192, 171)')
        chart_data['clearRate']['datasets'][3]['backgroundColor'].append('rgb(255, 242, 128)')
        chart_data['clearRate']['datasets'][4]['backgroundColor'].append('rgb(166, 227, 157)')
        chart_data['clearRate']['datasets'][5]['backgroundColor'].append('#C6C6C6')

    json_str = json.dumps(chart_data['clearRate'], ensure_ascii=False)
    return HttpResponse(json_str, content_type='application/json; charset=UTF-8')


def is_xml_http_request(req: HttpRequest) -> bool:
    return req.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

users/views/cleardata.py
from django.core.paginator import Paginator
from django.db.models import Prefetch
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from main.models import Bad_Count, Extra_Option, Medal, Music, Sran_Level
from main.services import get_folder_status

from users.models import CustomUser


def cleardata(request: HttpRequest, username: str, sran_level: int) -> HttpResponse:
    """ クリア状況 """

    selected_user = get_object_or_404(CustomUser, username=username, is_active=True)

    if sran_level <= 0 or sran_level > Sran_Level.MAX:
        raise Http404

    music_query = Music.objects.filter(sran_level=sran_level).order_by('level', 'title').select_related('difficulty',
                                                                                                        'level')
    music_count = music_query.count()

    music_query = music_query.prefetch_related(
        Prefetch('medal_set', queryset=Medal.objects.filter(user=selected_user), to_attr='user_medal'),
        Prefetch('bad_count_set', queryset=Bad_Count.objects.filter(user=selected_user), to_attr='user_bad_count'),
        Prefetch('extra_option_set', queryset=Extra_Option.objects.filter(user=selected_user, hard=True),
                 to_attr='user_extra_option')
    )

    music_data = []
    for music in music_query:
        medal = None
        bad_count = None
        extra_option = None
        clear_status = Medal.ClearStatus.NO_PLAY.value
        updated_at = None

        if hasattr(music, 'user_medal') and music.user_medal:
            medal = music.user_medal[0]
            updated_at = medal.updated_at

        if hasattr(music, 'user_bad_count') and music.user_bad_count:
            bad_count = music.user_bad_count[0]
            if not updated_at or bad_count.updated_at > updated_at:
                updated_at = bad_count.updated_at

        if hasattr(music, 'user_extra_option') and music.user_extra_option:
            extra_option = music.user_extra_option[0]

        if medal:
            clear_status = medal.get_clear_status(bad_count=bad_count, extra_option=extra_option).value

        music_data.append({
            'id': music.id,
            'level': music.level.level,
            'title': music.title,
            'difficulty': music.difficulty.difficulty_short(),
            'bpm': music.bpm,
            'medal': medal.medal if medal else None,
            'bad_count': bad_count.bad_count if bad_count else None,
            'clear_status': clear_status,
            'updated_at': updated_at,
        })

    paginator = Paginator(music_data, 25)
    page = request.GET.get('page')
    music_list = paginator.get_page(page)

    context = {
        'selected_user': selected_user,
        'sran_level': sran_level,
        'music_list': music_list,
        'music_count': music_count,
        'folder_status': get_folder_status(selected_user, music_query).value,
    }
    return render(request, 'users/cleardata.html', context)

users/views/deactivate.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from main.models import Bad_Count, Extra_Option, Medal


@login_required
def deactivate(request: HttpRequest) -> HttpResponse:
    """ アカウント削除 """

    # 自ユーザーを取得
    myself = request.user

    # POSTでアクセスされた場合
    if request.method == 'POST':
        # クリアメダルを取得
        medal = Medal.objects.filter(user=myself)
        if medal:
            # メダルが存在すれば削除
            medal.delete()

        # BAD数を取得
        bad_count = Bad_Count.objects.filter(user=myself)
        if bad_count:
            # BAD数が存在すれば削除
            bad_count.delete()

        # エクストラオプションを取得
        extra_option = Extra_Option.objects.filter(user=myself)
        if extra_option:
            # エクストラオプションが存在すれば削除
            extra_option.delete()

        # アカウントを無効にする
        myself.is_active = False
        # 保存
        myself.save()

        # ログアウトページにリダイレクト
        return redirect('/auth/logout/?next=/')

    return render(request, 'users/deactivate.html')

users/views/download.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpRequest, HttpResponse

from google.cloud import storage


@login_required
def download(request: HttpRequest, file_type: str) -> HttpResponse:
    """
    ファイルダウンロード
    :param request:
    :param file_type: ダウンロードするファイルの種類
    """

    if file_type == 'csv':
        if request.user.premium:
            env = getattr(settings, 'ENV', None)
            if env is None:
                raise Exception('failed to read env')

            try:
                bucket = storage.Client().bucket(env('GCP_INTERNAL_BUCKET'))
                blob = bucket.blob(f'csv/export/{request.user.username}.csv')
                response = HttpResponse(blob.download_as_string(), content_type='text/csv; charset=utf-8')
            except FileNotFoundError:
                raise Http404
            except Exception as e:
                raise Exception(f'failed to download CSV: {e}')

            response['Content-Disposition'] = f'attachment; filename={request.user.username}.csv'
        else:
            raise PermissionDenied
        return response
    else:
        raise Http404

users/views/list.py
from django.core.paginator import Paginator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from users.models import CustomUser


def list_users(request: HttpRequest) -> HttpResponse:
    """ ユーザーリスト """

    users = CustomUser.objects.filter(is_active=True).exclude(pk=1).order_by('id')

    paginator = Paginator(users, 50)
    page = request.GET.get('page')
    users = paginator.get_page(page)

    context = {'users': users}
    return render(request, 'users/list.html', context)

users/templates/users/list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}登録ユーザーリスト - スパランドットコム{% endblock %}

{% block extrahead %}
<meta property="og:title" content="登録ユーザーリスト - スパランドットコム" />
<meta property="og:type" content="article" />
<meta name="description" content="スパランドットコムの登録ユーザーリストページです。">
{% endblock %}

{% block content %}
<h1 class="page-header">{% bootstrap_icon "user" %} 登録ユーザーリスト</h1>
<p>スパランドットコムに登録しているユーザーの一覧です。</p>
<br>
<div class="table-responsive">
    <table class="user-list table table-bordered">
        <thead>
            <th class="col-sm-1">#</th>
            <th class="col-sm-2">ユーザー名</th>
            <th class="col-sm-2">プレイヤー名</th>
            <th class="col-sm-1">地域</th>
            <th class="col-sm-6">コメント</th>
        </thead>
        <tbody>
            {% for selected_user in users %}
            <tr{% if selected_user.username == user.username %} id="myself"{% endif %}>
                <td class="no">{{ forloop.counter0 | add:users.start_index }}</td>
                <td class="username"><a href="{% url 'users:mypage' selected_user.username %}">{{ selected_user.username }}</a>{% if selected_user.premium %} <span class="premium">★</span>{% endif %}</td>
                <td class="player_name">{{ selected_user.player_name|default:'-' }}</td>
                <td class="location">{{ selected_user.location|default:'-' }}</td>
                <td class="comment">{{ selected_user.profile|default:'-' }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div style="text-align:center">
    <ul class="pagination">
        {% if users.has_previous %}
        <li>
            <a href="?page={{ users.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">前へ</span>
            </a>
        </li>
        {% endif %}

        {% for page in users.paginator.page_range %}
            {% if page == users.number %}
            <li class="active"><span>{{ page }}</span></li>
            {% else %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if users.has_next %}
        <li>
            <a href="?page={{ users.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">次へ</span>
            </a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

users/templates/users/mypage.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block title %}{{ selected_user.player_name|default:selected_user.username }} - スパランドットコム{% endblock %}

{% block extrahead %}
<meta property="og:title" content="{{ selected_user.player_name|default:selected_user.username }} - スパランドットコム" />
<meta property="og:type" content="article" />
<meta name="description" content="スパランドットコムのプロフィールページです。">
<script src="{% static 'js/mypage.js' %}"></script>
{% endblock %}

{% block content %}
<h1 class="page-header">{% bootstrap_icon "book" %} プロフィール</h1>
<h2>
    {% if selected_user.premium %}
    <span class="premium">★</span>
    {% endif %}
    {{ selected_user.player_name|default:selected_user.username }}
</h2>
<p class="username"><i class="fa fa-twitter" aria-hidden="true"></i> <a href="https://twitter.com/{{ selected_user.username }}" target="_blank">@{{ selected_user.username }}</a></p>
<p>ポプともID: {{ selected_user.split_poputomo_id|default:'------' }}</p>
<p>都道府県: {{ selected_user.location|default:'------' }}</p>
<p>コメント:<br>{{ selected_user.profile|default:'------' }}</p>
<p>登録日時: {{ selected_user.date_joined|date:"Y/n/d G:i" }}</p>
{% if selected_user == user %}
<p>最終ログイン日時: {{ selected_user.last_login|date:"Y/n/d G:i" }}</p>
{% endif %}

{% if selected_user == user %}
<a href="{% url 'users:settings' %}" class="btn btn-default">{% bootstrap_icon "pencil" %} 編集する</a>
{% endif %}

<a href="https://twitter.com/intent/tweet?text={{ selected_user.player_name|default:selected_user.username }}さんのプロフィールページです。&url={{ request.build_absolute_uri }}&hashtags=スパランドットコム" class="btn btn-info"><i class="fa fa-twitter" aria-hidden="true"></i> ツイートする</a>

{% if selected_user.cleardata_privacy == 1 or selected_user == user %}
<br /><br />
<a href="{% url 'users:statistics' selected_user.username %}" class="btn btn-default">{% bootstrap_icon "book" %} 統計</a>
{% endif %}

<h2 class="clear-data page-header">
    {% if selected_user.cleardata_privacy == 2 and selected_user == user %}
    {% bootstrap_icon "star-empty" %} クリア状況 (非公開)
    {% else %}
    {% bootstrap_icon "star-empty" %} クリア状況
    {% endif %}
</h2>
{% if selected_user.cleardata_privacy == 1 or selected_user == user %}
    <p>グラフをクリックすると各レベルごとの詳しいクリア状況を確認できます。</p>
    {% for s_lv in s_lv_range %}
    Lv{{ s_lv }}
    <div id="slv-{{ s_lv }}" class="clear-graph graph">
        <a href="{% url 'users:cleardata' selected_user.username s_lv %}"><span class="bar" style="background-color:#FFFFFF;"><div class="loading"></div></span></a>
    </div>
    {% endfor %}
    <script>$(function() { getPercentageOfClear({{ selected_user.id }}); });</script>
{% else %}
    <p>クリアデータは非公開に設定されています。</p>
{% endif %}

<h2 class="updated-recently page-header">
    {% if selected_user.updated_recently_privacy == 2 and selected_user == user %}
    {% bootstrap_icon "dashboard" %} 最近更新した曲 (非公開)
    {% else %}
    {% bootstrap_icon "dashboard" %} 最近更新した曲
    {% endif %}
</h2>
{% if selected_user.updated_recently_privacy == 1 or selected_user == user %}
    <table class="music-list table table-condensed">
        <thead>
            <th>Lv</th>
            <th>曲名</th>
            <th>BPM</th>
            <th>メダル</th>
            <th>BAD数</th>
            <th>更新日時</th>
        </thead>
        <tbody>
        {% for data in recent_data %}
        <tr id="music-{{ data.music_id }}" class="{{ data.clear_status }}">
            <td class="level">{{ data.level }} ({{ data.sran_level }})</td>
            <td class="title"><a href="{% url 'main:ranking_detail' data.music_id %}">{{ data.title }} ({{ data.difficulty }})</a></td>
            <td class="bpm">{{ data.bpm|default:'-' }}</td>
            <td class="medal">
                {% if data.medal and data.medal != 12 %}
                <img src="{% static '' %}img/medal/{{ data.medal }}.png" width="18" height="18">
                {% else %}
                -
                {% endif %}
            </td>
            <td class="bad_count">
                {% if data.bad_count == 0 %}
                0
                {% else %}
                {{ data.bad_count|default:'-' }}
                {% endif %}
            </td>
            <td class="updated_at">{{ data.updated_at|date:"Y/n/d G:i"|default:'-' }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>最近更新した曲は非公開に設定されています。</p>
{% endif %}
{% endblock %}

users/templates/users/settings.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}設定 - スパランドットコム{% endblock %}

{% block extrahead %}
<meta property="og:title" content="設定 - スパランドットコム" />
<meta property="og:type" content="article" />
<meta name="description" content="スパランドットコムの設定ページです。">
{% endblock %}

{% block content %}
<div class="settings">
    <h1 class="page-header">{% bootstrap_icon "cog" %} 設定</h1>

    {% if messages %}
    <ul id="message-box">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% bootstrap_icon "info-sign" %} {{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <section id="account" class="settings-panel">
        <h2 class="settings-header page-header">{% bootstrap_icon "user" %} アカウント</h2>
        <form class="settings-form form" action="./" method="post">{% csrf_token %}
            {% bootstrap_form custom_user_form %}
            <input class="btn btn-primary" type="submit" name="account" value="保存する">
        </form>
    </section>

    <section id="privacy" class="settings-panel">
        <h2 class="settings-header page-header">{% bootstrap_icon "ok" %} 公開設定</h2>
        <form class="settings-form form" action="./" method="post">{% csrf_token %}
            {% bootstrap_form privacy_form %}
            <input class="btn btn-primary" type="submit" name="privacy" value="保存する">
        </form>
    </section>

    <section id="theme" class="settings-panel">
        <h2 class="settings-header page-header">{% bootstrap_icon "picture" %} テーマ</h2>
        <form class="settings-form form" action="./" method="post">{% csrf_token %}
            {% bootstrap_form theme_form %}
            <input class="btn btn-primary" type="submit" name="themes" value="保存する">
        </form>
    </section>

    <section id='export' class="settings-panel">
        <h2 class="settings-header page-header">{% bootstrap_icon "export" %} CSV エクスポート <span class="premium">★</span></h2>
        <p>クリアデータを CSV ファイルで保存できます。</p>
        <p>CSV ファイルは毎日 AM 0:30 頃に最新のデータに更新されます。</p>
        <p>※ 文字コードは "UTF-8" で出力されます。</p>
        <br>
        {% if user.premium %}
        <a href="{% url 'users:download' 'csv' %}"><button class="btn btn-success" type="button">{% bootstrap_icon "download" %} ダウンロードする</button></a>
        {% else %}
        <a href="{% url 'main:premium' %}" target="_blank"><button class="btn btn-success disabled" type="button">{% bootstrap_icon "download" %} ダウンロードする</button></a>
        {% endif %}
    </section>

    <section id="deactivate" class="settings-panel settings-panel-danger">
        <h2 class="settings-header page-header">{% bootstrap_icon "trash" %} アカウント削除</h2>
        <p class="danger">一度アカウントを削除すると、二度と元に戻せません。十分ご注意ください。</p>
        <br>
        <a href="{% url 'users:deactivate' %}"><span class="btn btn-danger">{% bootstrap_icon "alert" %} アカウントを削除する</span></a>
    </section>
</div><!-- settings -->
{% endblock %}