main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import api, difflist, difflist_level_select, edit, index, level, level_select, omikuji, ranking, \
    ranking_detail, ranking_level_select, search

app_name = 'main'
urlpatterns = [
    path('', index.index, name='index'),
    path('search/', search.search, name='search'),
    path('level/', level_select.level_select, name='level_select'),
    path('level/<int:level>/', level.level, name='level'),
    path('difflist/', difflist_level_select.difflist_level_select, name='difflist_level_select'),
    path('difflist/<int:sran_level>/', difflist.difflist, name='difflist'),
    path('edit/<int:music_id>/', edit.edit, name='edit'),
    path('ranking/', ranking_level_select.ranking_level_select, name='ranking_level_select'),
    path('ranking/<int:sran_level>/', ranking.ranking, name='ranking'),
    path('ranking/detail/<int:music_id>/', ranking_detail.ranking_detail, name='ranking_detail'),
    path('omikuji/', omikuji.omikuji, name='omikuji'),
    path('premium/', TemplateView.as_view(template_name="main/premium.html"), name='premium'),
    path('api/get_clear_status/<int:music_id>/', api.get_clear_status, name='get_clear_status'),
    path('api/get_bad_count/<int:music_id>/', api.get_bad_count, name='get_bad_count'),
    path('api/get_medal/<int:music_id>/', api.get_medal, name='get_medal'),
    path('api/get_latest_updated_at/<int:music_id>/', api.get_latest_updated_at, name='get_latest_updated_at'),
    path('api/get_bad_count_avg/<int:music_id>/', api.get_bad_count_avg, name='get_bad_count_avg'),
    path('api/get_myrank/<int:music_id>/', api.get_myrank, name='get_myrank'),
    path('api/get_medal_count/<int:music_id>/', api.get_medal_count, name='get_medal_count'),
    path('api/get_folder_lamp/<int:level>/', api.get_folder_lamp, name='get_folder_lamp'),
]

srandom/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('main.urls')),
    path('mastermind/', admin.site.urls),
    path('maintenance-mode/', include('maintenance_mode.urls')),
    path('auth/', include(('django.contrib.auth.urls', 'auth'))),
    path('social/', include(('social_django.urls', 'social'))),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    import debug_toolbar
    # ref. https://docs.djangoproject.com/ja/4.1/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + staticfiles_urlpatterns()

users/urls.py
from django.urls import path

from .views import api, cleardata, deactivate, download, list, mypage, settings, statistics

app_name = 'users'
urlpatterns = [
    path('list/', list.list_users, name='list'),
    path('settings/', settings.settings, name='settings'),
    path('deactivate/', deactivate.deactivate, name='deactivate'),
    path('<username>/', mypage.mypage, name='mypage'),
    path('<username>/statistics/', statistics.statistics, name='statistics'),
    path('<username>/cleardata/<int:sran_level>/', cleardata.cleardata, name='cleardata'),
    path('download/<file_type>/', download.download, name='download'),
    path('api/get_percentage_of_clear/<int:user_id>/', api.get_percentage_of_clear, name='get_percentage_of_clear'),
    path('api/get_activity_map/', api.get_activity_map, name='get_activity_map'),
    path('api/get_clear_rate/', api.get_clear_rate, name='get_clear_rate'),
]

templates/503.html
{% extends "base.html" %}

{% block extrahead %}
<meta name="description" content="スパランドットコムの503エラーページです。">
{% endblock %}

{% block title %}サーバーメンテナンス中です - スパランドットコム{% endblock %}

{% block content %}
<h1 class="page-header">サーバーメンテナンス中です</h1>
<p>いつも当サイトをご利用頂きありがとうございます。</p>
<p>大変申し訳ございません。只今サーバーメンテナンス中です。</p>
<p>しばらく時間をおいてから再度アクセスして頂きますようお願い致します。m(_ _)m</p>

<h2 class="page-header">お問い合わせ</h2>
<p>当サイトに関するお問い合わせは以下の連絡先までお願い致します。</p>
<br>
<p>Twitter: <a href="https://twitter.com/sapuri_tappuri" target="_blank">@sapuri_tappuri</a></p>
<p>E-mail: <a href="mailto:info@srandom.com">info@srandom.com</a></p>
{% endblock %}

templates/base.html
{% load static %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if user.theme.id == 2 %}
        <meta name="theme-color" content="#181818">
    {% else %}
        <meta name="theme-color" content="#FF5814">
    {% endif %}
    <meta property="og:url" content="https://srandom.com" />
    <meta property="og:image" content="{% static 'img/site_image.png' %}"/>
    <meta property="og:site_name" content="スパランドットコム" />
    <meta property="og:description" content="スパランドットコムは、ポップンミュージックのスパラン愛好家のためのクリア状況管理サイトです。" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@sapuri_tappuri" />
    <title>{% block title %}スパランドットコム - ポップンミュージックのスパラン愛好家のためのクリア状況管理サイト{% endblock %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% if user.theme.id == 2 %}<link rel="stylesheet" href="{% static 'css/dark.css' %}">{% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>const STATIC_URL = "{% static "" %}"</script>
    <script src="{% static 'js/global.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    {% block extrahead %}{% endblock %}
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-2PMWCRQZDR"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        {% if user.is_authenticated %}ga('set', 'userId', '{{ user.username }}');
        gtag('config', 'G-2PMWCRQZDR', {
            'user_id': '{{ user.username }}'
        });
        {% else %}
        gtag('config', 'G-2PMWCRQZDR');
        {% endif %}
    </script>
</head>
<body>
    <nav id="header" class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">スパランドットコム</a>
            </div>
            {% if user.is_authenticated %}
            <div class="collapse navbar-collapse target">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'main:level_select' %}">公式難易度表</a></li>
                    <li><a href="{% url 'main:difflist_level_select' %}">S乱難易度表</a></li>
                    <li><a href="{% url 'main:ranking_level_select' %}">ランキング</a></li>
                    <li><a href="{% url 'main:omikuji' %}">おみくじ</a></li>
                    {% if not user.premium %}
                    <li><a href="{% url 'main:premium' %}" class="premium">プレミアム</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown-toggle" data-toggle="dropdown">
                        {% if user.premium %}
                        <a href="{% url 'users:mypage' user.username %}"><span class="premium">★{{ user.username }}</span> <span class="caret"></span></a>
                        {% else %}
                        <a href="{% url 'users:mypage' user.username %}">@{{ user.username }} <span class="caret"></span></a>
                        {% endif %}
                    </li>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'users:mypage' user.username %}">{% bootstrap_icon "book" %} マイページ</a></li>
                        <li><a href="{% url 'users:settings' %}">{% bootstrap_icon "cog" %} 設定</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'auth:logout' %}?next={% url 'main:index' %}">{% bootstrap_icon "log-out" %} ログアウト</a></li>
                    </ul>
                </ul>
            </div>
            {% else %}
            <div class="collapse navbar-collapse target">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'social:begin' 'twitter' %}">{% bootstrap_icon "log-in" %} Twitterでログイン</a></li>
                </ul>
            </div>
            {% endif %}
        </div>
    </nav><!-- /#header -->

    <div id="main" class="container">
        <div class="content col-xs-12 col-md-10">
            {% block content %}{% endblock %}
        </div><!-- /#main -->

        <div class="sidebar col-xs-12 col-md-2">
            {% if user.is_authenticated %}
            <p>{% bootstrap_icon "th-list" %} メニュー</p>
            <ul>
                <li><a class="no-decoration" href="{% url 'main:index' %}">トップ</a></li>
                <li><a class="no-decoration" href="{% url 'main:level_select' %}">{% bootstrap_icon "list-alt" %} 公式難易度表</a></li>
                <li><a class="no-decoration" href="{% url 'main:difflist_level_select' %}">{% bootstrap_icon "list-alt" %} S乱難易度表</a></li>
                <li><a class="no-decoration" href="{% url 'main:ranking_level_select' %}">{% bootstrap_icon "king" %} ランキング</a></li>
                <li><a class="no-decoration" href="{% url 'main:omikuji' %}">{% bootstrap_icon "gift" %} おみくじ</a></li>
                <li><a class="no-decoration" href="{% url 'main:premium' %}">{% bootstrap_icon "star" %} 開発者に寄付</a></li>
                <li><a class="no-decoration" href="{% url 'users:list' %}">{% bootstrap_icon "user" %} 登録ユーザー</a></li>
                <li><a class="no-decoration" href="{% url 'users:mypage' user.username %}">{% bootstrap_icon "book" %} マイページ</a></li>
                <li><a class="no-decoration" href="{% url 'users:settings' %}">{% bootstrap_icon "cog" %} 設定</a></li>
            </ul>
            {% endif %}
        </div><!-- /.sidebar -->
    </div><!-- /#main -->

    <div id="footer">
        <div class="container">
            <div class="footer-left">
                <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-related="srandomcom,sapuri_tappuri" data-dnt="true" data-show-count="false">Tweet</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                <p>スパランドットコムは、ポップンミュージックのスパラン愛好家のためのクリア状況管理サイトです。</p>
            </div>
            <div class="footer-right">
                <p>開発・運営: <a href="https://twitter.com/sapuri_tappuri" target="_blank">@sapuri_tappuri</a></p>
                <p>&copy; 2016-{% now 'Y' %} srandom.com</p>
            </div>
        </div><!-- /.container -->
    </div><!-- /#footer -->
    {% bootstrap_javascript %}
</body>
</html>