main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import api, difflist, difflist_level_select, edit, index, level, level_select, omikuji, ranking, \
    ranking_detail, ranking_level_select, search

app_name = 'main'
urlpatterns = [
    path('', index.index, name='index'),
    path('search/', search.search, name='search'),
    path('level/', level_select.level_select, name='level_select'),
    path('level/<int:level>/', level.level, name='level'),
    path('difflist/', difflist_level_select.difflist_level_select, name='difflist_level_select'),
    path('difflist/<int:sran_level>/', difflist.difflist, name='difflist'),
    path('edit/<int:music_id>/', edit.edit, name='edit'),
    path('ranking/', ranking_level_select.ranking_level_select, name='ranking_level_select'),
    path('ranking/<int:sran_level>/', ranking.ranking, name='ranking'),
    path('ranking/detail/<int:music_id>/', ranking_detail.ranking_detail, name='ranking_detail'),
    path('omikuji/', omikuji.omikuji, name='omikuji'),
    path('premium/', TemplateView.as_view(template_name="main/premium.html"), name='premium'),
    path('api/get_clear_status/<int:music_id>/', api.get_clear_status, name='get_clear_status'),
    path('api/get_bad_count/<int:music_id>/', api.get_bad_count, name='get_bad_count'),
    path('api/get_medal/<int:music_id>/', api.get_medal, name='get_medal'),
    path('api/get_latest_updated_at/<int:music_id>/', api.get_latest_updated_at, name='get_latest_updated_at'),
    path('api/get_bad_count_avg/<int:music_id>/', api.get_bad_count_avg, name='get_bad_count_avg'),
    path('api/get_myrank/<int:music_id>/', api.get_myrank, name='get_myrank'),
    path('api/get_medal_count/<int:music_id>/', api.get_medal_count, name='get_medal_count'),
    path('api/get_folder_lamp/<int:level>/', api.get_folder_lamp, name='get_folder_lamp'),
]

srandom/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('main.urls')),
    path('mastermind/', admin.site.urls),
    path('maintenance-mode/', include('maintenance_mode.urls')),
    path('auth/', include(('django.contrib.auth.urls', 'auth'))),
    path('social/', include(('social_django.urls', 'social'))),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    import debug_toolbar
    # ref. https://docs.djangoproject.com/ja/4.1/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + staticfiles_urlpatterns()

users/urls.py
from django.urls import path

from .views import api, cleardata, deactivate, download, list, mypage, settings, statistics

app_name = 'users'
urlpatterns = [
    path('list/', list.list_users, name='list'),
    path('settings/', settings.settings, name='settings'),
    path('deactivate/', deactivate.deactivate, name='deactivate'),
    path('<username>/', mypage.mypage, name='mypage'),
    path('<username>/statistics/', statistics.statistics, name='statistics'),
    path('<username>/cleardata/<int:sran_level>/', cleardata.cleardata, name='cleardata'),
    path('download/<file_type>/', download.download, name='download'),
    path('api/get_percentage_of_clear/<int:user_id>/', api.get_percentage_of_clear, name='get_percentage_of_clear'),
    path('api/get_activity_map/', api.get_activity_map, name='get_activity_map'),
    path('api/get_clear_rate/', api.get_clear_rate, name='get_clear_rate'),
]

main/views/api.py
from zoneinfo import ZoneInfo

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db.models import Avg, Count
from django.http import HttpRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_GET

from main.models import Bad_Count, Extra_Option, Medal, Music
from main.services import get_folder_status

from users.models import CustomUser


@require_GET
def get_clear_status(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲のクリア状況を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user and (not user.is_active or user.cleardata_privacy == 2):
        raise PermissionDenied

    bad_count = Bad_Count.objects.filter(music_id=music_id, user_id=user_id).first()
    medal = Medal.objects.filter(music_id=music_id, user_id=user_id).first()
    extra_option = Extra_Option.objects.filter(music_id=music_id, user_id=user_id, hard=True).first()

    clear_status = Medal.ClearStatus.NO_PLAY.value
    if medal:
        clear_status = medal.get_clear_status(bad_count=bad_count, extra_option=extra_option).value

    return JsonResponse({'clear_status': clear_status})


@require_GET
def get_bad_count(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲のBAD数を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user:
        if not user.is_active or user.cleardata_privacy == 2:
            raise PermissionDenied

    try:
        bad_count = Bad_Count.objects.get(music_id=music_id, user_id=user_id).bad_count
    except ObjectDoesNotExist:
        bad_count = None

    return JsonResponse({'bad_count': bad_count})


@require_GET
def get_medal(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲のメダルを返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user:
        if not user.is_active or user.cleardata_privacy == 2:
            raise PermissionDenied

    try:
        medal = Medal.objects.get(music_id=music_id, user_id=user_id).medal
    except ObjectDoesNotExist:
        medal = None

    return JsonResponse({'medal': medal})


@require_GET
def get_latest_updated_at(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲の最新の更新日時を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user:
        if not user.is_active or user.cleardata_privacy == 2:
            raise PermissionDenied

    try:
        medal = Medal.objects.get(music_id=music_id, user_id=user_id)
        updated_at = medal.updated_at.astimezone(ZoneInfo('Asia/Tokyo'))

        context = {
            'is_active': True,
            'year': updated_at.year,
            'month': updated_at.month,
            'day': updated_at.day,
            'hour': updated_at.hour,
            'minute': updated_at.minute,
            'second': updated_at.second
        }
    except ObjectDoesNotExist:
        context = {'is_active': False}

    return JsonResponse(context)


@require_GET
def get_bad_count_avg(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲の平均BAD数を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    # BAD数の平均を計算 (小数点以下四捨五入)
    bad_count_avg = Bad_Count.objects.filter(music_id=music_id).aggregate(Avg('bad_count'))['bad_count__avg']

    if bad_count_avg is None:
        bad_count_avg = -1
    else:
        bad_count_avg = round(bad_count_avg)

    return JsonResponse({'bad_count_avg': bad_count_avg})


@login_required
@require_GET
def get_myrank(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲の順位を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user:
        if not user.is_active or user.cleardata_privacy == 2:
            raise PermissionDenied

    bad_count_list = Bad_Count.objects.filter(music=music_id).order_by('bad_count')
    bad_count_num = 0
    myrank = 0
    tmp_rank = 0
    previous_bad_count = -1

    for bad_count in bad_count_list:
        # BAD数が前後で重複しない場合、順位を更新
        if bad_count.bad_count != previous_bad_count:
            tmp_rank = bad_count_num + 1

        # 自分の記録が見つかれば、myrank にランクを格納
        if bad_count.user.id == user.id:
            myrank = tmp_rank

        previous_bad_count = bad_count.bad_count
        bad_count_num += 1

    return JsonResponse({
        'myrank': myrank,
        'bad_count_num': bad_count_num
    })


@require_GET
def get_medal_count(request: HttpRequest, music_id: int) -> JsonResponse:
    """
    指定された曲の各メダルの枚数を返す
    """
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    medals = Medal.objects.filter(music_id=music_id).values('medal').annotate(total=Count('medal')).order_by('medal')

    medal_count_list = [0] * 11
    medal_count_total = 0
    for medal in medals:
        if 1 <= medal['medal'] <= 11:
            i = medal['medal'] - 1
            medal_count_list[i] = medal['total']
            medal_count_total += medal['total']

    context = {
        'medal_count_list': medal_count_list,
        'medal_count_total': medal_count_total
    }

    return JsonResponse(context)


@require_GET
def get_folder_lamp(request: HttpRequest, level: int) -> JsonResponse:
    if not is_xml_http_request(request):
        return JsonResponse({'error': 'invalid access'})

    user_id = request.GET.get('user_id', request.user.id)
    user = get_object_or_404(CustomUser, pk=user_id)

    if user != request.user and (not user.is_active or user.cleardata_privacy == 2):
        raise PermissionDenied

    is_srandom = request.GET.get('is_srandom', 'false') == 'true'
    level = int(level)
    music_query = Music.objects.filter(sran_level=level) if is_srandom else Music.objects.filter(level=50 - level + 1)

    folder_status = get_folder_status(user, music_query)

    return JsonResponse({'folder_lamp': folder_status.value})


def is_xml_http_request(req: HttpRequest) -> bool:
    return req.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

main/views/difflist.py
from django.core.paginator import Paginator
from django.db.models import Prefetch
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import render

from main.models import Bad_Count, Extra_Option, Medal, Music, Sran_Level
from main.services import get_folder_status


def difflist(request: HttpRequest, sran_level: int) -> HttpResponse:
    """ 難易度表 """

    sran_level = int(sran_level)

    if sran_level <= 0 or sran_level > Sran_Level.MAX:
        raise Http404

    music_query = Music.objects.filter(sran_level=sran_level).order_by('level', 'title').select_related(
        'difficulty', 'level')
    music_count = music_query.count()

    folder_status = Medal.ClearStatus.NO_PLAY
    if request.user.is_authenticated:
        folder_status = get_folder_status(request.user, music_query)

        music_query = music_query.prefetch_related(
            Prefetch('medal_set', queryset=Medal.objects.filter(user=request.user), to_attr='user_medal'),
            Prefetch('bad_count_set', queryset=Bad_Count.objects.filter(user=request.user), to_attr='user_bad_count'),
            Prefetch('extra_option_set', queryset=Extra_Option.objects.filter(user=request.user, hard=True),
                     to_attr='user_extra_option')
        )

    music_data = []
    for music in music_query:
        medal = None
        bad_count = None
        extra_option = None
        clear_status = Medal.ClearStatus.NO_PLAY.value
        updated_at = None

        if request.user.is_authenticated:
            if hasattr(music, 'user_medal') and music.user_medal:
                medal = music.user_medal[0]
                updated_at = medal.updated_at

            if hasattr(music, 'user_bad_count') and music.user_bad_count:
                bad_count = music.user_bad_count[0]
                if not updated_at or bad_count.updated_at > updated_at:
                    updated_at = bad_count.updated_at

            if hasattr(music, 'user_extra_option') and music.user_extra_option:
                extra_option = music.user_extra_option[0]

            if medal:
                clear_status = medal.get_clear_status(bad_count=bad_count, extra_option=extra_option).value

        music_data.append({
            'id': music.id,
            'level': music.level.level,
            'title': music.title,
            'difficulty': music.difficulty.difficulty_short(),
            'bpm': music.bpm,
            'medal': medal.medal if medal else None,
            'bad_count': bad_count.bad_count if bad_count else None,
            'clear_status': clear_status,
            'updated_at': updated_at,
        })

    paginator = Paginator(music_data, 25)
    page = request.GET.get('page')
    music_list = paginator.get_page(page)

    context = {
        'sran_level': sran_level,
        'music_list': music_list,
        'music_count': music_count,
        'folder_status': folder_status.value,
    }

    return render(request, 'main/difflist.html', context)

main/views/difflist_level_select.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from main.models import Sran_Level


def difflist_level_select(request: HttpRequest) -> HttpResponse:
    """ 難易度表: S乱レベル選択 """

    s_lv_range = range(Sran_Level.MAX, Sran_Level.MIN - 1, -1)

    context = {
        's_lv_range': s_lv_range
    }

    return render(request, 'main/difflist_level_select.html', context)

main/views/index.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from main.forms import SearchForm
from main.models import Medal, Music

from social_django.models import UserSocialAuth


def index(request: HttpRequest) -> HttpResponse:
    """ トップページ """

    medal_num = Medal.objects.count()
    recent_medals = Medal.objects.order_by('-updated_at')[:10]

    recent_music_ids = list(recent_medals.values_list('music', flat=True))
    recent_music = Music.objects.filter(id__in=recent_music_ids)

    search_form = SearchForm(request.GET)

    user_google_ids = []
    if request.user.is_authenticated:
        user_google_ids = UserSocialAuth.objects.filter(user=request.user, provider="google-oauth2").values_list('uid',
                                                                                                                 flat=True)

    context = {
        'medal_num': medal_num,
        'recent_music': recent_music,
        'search_form': search_form,
        'is_signed_in_with_google': bool(user_google_ids),
        'user_google_ids': user_google_ids,
    }
    return render(request, 'main/index.html', context)

main/views/level_select.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from main.models import Level


def level_select(request: HttpRequest) -> HttpResponse:
    """ 公式難易度表: レベル選択 """

    lv_range = range(Level.MAX, Level.MIN - 1, -1)

    context = {
        'lv_range': lv_range
    }

    return render(request, 'main/level/level_select.html', context)

main/views/ranking_detail.py
from django.db.models import Avg
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from main.models import Bad_Count, Extra_Option, Medal, Music


def ranking_detail(request: HttpRequest, music_id: int) -> HttpResponse:
    music = get_object_or_404(Music, pk=music_id)

    medals = Medal.objects.filter(music=music).select_related('user')
    extra_options = Extra_Option.objects.filter(music=music, hard=True).select_related('user')

    medals_dict = {medal.user.id: medal for medal in medals}
    extra_options_dict = {option.user.id: option for option in extra_options}

    bad_count_list = Bad_Count.objects.filter(music=music).order_by('bad_count', 'updated_at')
    bad_count_avg_result = bad_count_list.aggregate(Avg('bad_count'))
    bad_count_avg = round(bad_count_avg_result['bad_count__avg']) if bad_count_avg_result[
        'bad_count__avg'] is not None else None

    rank, last_bad_count, results = 1, None, []

    for i, bad_count in enumerate(bad_count_list, start=1):
        if bad_count.bad_count != last_bad_count:
            rank = i
        last_bad_count = bad_count.bad_count

        medal = medals_dict.get(bad_count.user.id)
        extra_option = extra_options_dict.get(bad_count.user.id)

        if medal is None:
            status = Medal.ClearStatus.NO_PLAY.value
        else:
            status = medal.get_clear_status(bad_count, extra_option).value

        results.append({
            'rank': rank,
            'user': bad_count.user,
            'medal': medal,
            'bad_count': bad_count,
            'extra_option': extra_option,
            'status': status,
        })

    context = {
        'music': music,
        'bad_count_avg': bad_count_avg,
        'results': results,
    }

    return render(request, 'main/ranking_detail.html', context)

main/templates/main/delete.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}{{ music.title }}({{ music.difficulty }})を削除 - スパランドットコム{% endblock %}

{% block extrahead %}
<meta property="og:title" content="{{ music.title }}({{ music.difficulty }})を削除 - スパランドットコム" />
<meta property="og:type" content="article" />
<meta name="description" content="スパランドットコムの記録削除ページです。">
{% endblock %}

{% block content %}
<h1 class="page-header">{% bootstrap_icon "pencil" %} {{ music.title }} ({{ music.difficulty }})</h1>

<form action="./?next={% url 'main:difflist_level_select' %}" method="post">{% csrf_token %}
    <p class="danger">{% bootstrap_icon "alert" %} 本当に "{{ music.title }} ({{ music.difficulty }})" の記録を削除しますか？</p>
    <br>
    {% buttons %}
    <input class="btn btn-danger" type="submit" value="記録を削除する">
    {% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block extrahead %}
<meta property="og:title" content="スパランドットコム" />
<meta property="og:type" content="website" />
<meta name="description" content="スパランドットコムは、ポップンミュージックのスパラン愛好家のためのクリア状況管理サイトです。スパラン上級者の方はもちろん、初心者の方やこれから始める方にも気軽に使っていただけるサイトを目指します。">
{% endblock %}

{% block content %}
<h1 class="page-header">ようこそ！</h1>
{% if user.is_authenticated %}
    <p class="big">ようこそ {{ user.player_name|default:user.username }}さん！</p>
    {% if not user.player_name %}
    <p class="suggest-msg"><a href="{% url 'users:settings' %}">プロフィールを設定</a>してみましょう！</p>
    {% endif %}
    <p><a href="{% url 'main:difflist_level_select' %}">難易度表ページ</a>でクリア状況を記録できます！</p>
    <p><a href="{% url 'main:ranking_level_select' %}">ランキングページ</a>で各曲ごとのBAD数ランキングを閲覧できます！</p>
{% else %}
    <p>スパランドットコムをご利用頂くにはログインが必要です。</p>
    <p>Twitter アカウントをお持ちであればすぐにログインできます。</p>
    <p><a href="{% url 'social:begin' 'twitter' %}"><img src="{% static 'img/sign-in-with-twitter-gray.png' %}" alt="Sign in with Twitter" width="158" height="28"></a></p>
    <p>※ スパランドットコムが許可無くツイートすることはありません。</p>
{% endif %}

<div id="search">
    <form class="search-form has-feedback" action="{% url 'main:search' %}" method="get">
        {{ search_form.q }}
        <i class="glyphicon glyphicon-search form-control-feedback"></i>
    </form>
</div>

<h2 class="page-header danger">ログイン方法に関する重要なお知らせ</h2>
<div class="text-box">
    <p>(2023/02/07 更新)</p>
    <p><a href="https://twitter.com/TwitterDev/status/1621026986784337922" target="_blank" rel="noopener">Twitter APIの仕様変更</a>に伴い、今後Twitterによるログイン機能を廃止する可能性があります。</p>
    {% if user.is_authenticated %}
        <p>下のボタンからGoogleにログインしていただくと現在ログイン中のアカウントと関連付けされ、今後Googleアカウントによるログイン機能が提供された際にそのアカウントでログインできるようになります。</p>

        {% if is_signed_in_with_google %}
        <div style="color: green">
            <p>{% bootstrap_icon "ok" %} Googleアカウントと関連付けられています。</p>
            <ul style="list-style-type: disc">
                {% for google_id in user_google_ids %}
                <li>{{ google_id }}</li>
                {% endfor %}
            </ul>
        </div>
        <p>別のGoogleアカウントと関連付ける場合は再度下のボタンからGoogleにログインしてください。</p>
        {% endif %}

        <p><a href="{% url 'social:begin' 'google-oauth2' %}"><img src="{% static 'img/google_signin_light.png' %}" alt="Sign in with Google" width="191" height="46"></a></p>
    {% else %}
        <p>ログイン後にGoogleアカウントとの関連付けを行うと、今後Googleアカウントによるログイン機能が提供された際に現在使用しているアカウントでログインできるようになります。</p>
    {% endif %}
</div>

<h2 class="page-header">このサイトについて</h2>
<p>スパランドットコムは、<a href="https://p.eagate.573.jp/game/popn/unilab/index.html" target="_blank" rel="noopener">ポップンミュージック</a>のスパラン愛好家のためのクリア状況管理サイトです。</p>
<p>各楽曲ごとにスパラン(S乱)でのクリアメダルやBAD数を記録して管理できます。</p>
<p>スパラン上級者の方はもちろん、初心者の方やこれから始めようと思っている方にも気軽に使っていただけるサイトを目指します。</p>
<p>当サイトで扱っているS乱レベルは<a href="https://popn.wiki/%E3%81%9D%E3%81%AE%E4%BB%96/s%E4%B9%B1%E3%82%AF%E3%83%AA%E3%82%A2%E9%9B%A3%E6%98%93%E5%BA%A6%E8%A1%A8" target="_blank" rel="noopener">S乱クリア難易度表</a>に基いています。</p>
<p>楽曲情報は毎日自動的に更新されるので、常に最新の難易度表を使ってクリア状況を記録できます。</p>

<div id="activity" class="row">
    <div id="updated-recently" class="col-xs-12 col-md-5">
        <h3 class="page-header">最近更新された曲</h2>
        <p>現在 <b>{{ medal_num }}</b> 件の記録が登録されています！</p>
        <ul class="music-list">
            {% for music in recent_music %}
            <a href="{% url 'main:ranking_detail' music.id %}">
                <li class="music {% if music.difficulty.difficulty_short == 'EX' %}extra{% elif music.difficulty.difficulty_short == 'H' %}hyper{% elif music.difficulty.difficulty_short == 'N' %}normal{% else %}easy{% endif %}">
                    {{ music.title }} ({{ music.difficulty }})
                </li>
            </a>
            {% endfor %}
        </ul>
    </div>
    <div id="twitter-timeline" class="col-xs-12 col-md-7">
        <h3 class="page-header">ツイート</h2>
        <p>スパランドットコムに関するツイートのタイムライン</p>
        {% if user.theme.id == 2 %}
        <a class="twitter-timeline" data-height="440" data-theme="dark" data-dnt="true" href="https://twitter.com/srandomcom?ref_src=twsrc%5Etfw">Tweets by srandomcom</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        {% else %}
        <a class="twitter-timeline" data-height="440" data-link-color="#ff5814" data-dnt="true" href="https://twitter.com/srandomcom?ref_src=twsrc%5Etfw">Tweets by srandomcom</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        {% endif %}
    </div>
</div>

<h2 class="page-header">更新情報</h2>
<p>[2023/08/08] クリア状況ページの表の曲順が他のページの表と異なっていた問題を修正しました</p>
<p>[2022/10/04] メダル画像をUniLab仕様に変更しました</p>
<p>[2019/11/04] 難易度表のレイアウトを変更しました</p>
<p>[2019/05/03] S乱難易度表Wikiの移転に対応しました</p>
<p>[2018/09/14] S乱難易度表の変更に対応しました</p>
<p>[2017/09/08] 統計情報ページを試験公開しました</p>
<p>[2017/07/02] Twitterのユーザー名に絵文字が入っているとログインエラーが発生する問題を修正しました</p>
<p>[2017/02/06] プロフィールページにツイートボタンを設置しました</p>
<p>[2016/12/30] ダークテーマのスタイルを調整しました</p>
<p>[2016/12/23] S乱難易度表のLv16分割に対応しました</p>
<p>[2016/12/04] 難易度表ページの読み込みに時間がかかることがあるため、25件ごとにページを分割しました</p>
<p>[2016/12/02] サイトを常時SSL化しました</p>
<p>[2016/12/01] おみくじの条件を保存し、連続して引くことができるようにしました</p>
<p>[2016/12/01] 記録編集ページで編集履歴を閲覧できるようにしました</p>
<p>[2016/09/14] ニュース一覧ページを追加しました</p>
<p>[2016/06/19] 楽曲検索機能を追加しました</p>
<p>[2016/05/26] テーマ変更機能を追加しました</p>
<p>[2016/05/19] CSVエクスポート機能を追加しました</p>
<p>[2016/05/09] プロフィールページなど、一部のページはログインしなくても閲覧できるようにしました</p>
<p>[2016/05/06] 難易度表及びランキングページの読み込みを高速化しました</p>
<p>[2016/03/22] プレミアムユーザー機能を追加しました</p>
<p>[2016/03/19] テーブルを少しコンパクトにしました</p>
<p>[2016/03/13] BAD数の入力を必須とせず、メダルのみの登録もできるようにしました</p>
<p>[2016/03/12] おみくじページでレベルを範囲指定できるようにしました</p>
<p>[2016/03/10] ランキング詳細ページからでも記録を編集できるようにしました</p>
<p>[2016/03/09] おみくじ機能を追加しました</p>
<p>[2016/03/08] 一部のブラウザでBAD数を入力しなくても記録を登録できてしまう問題を修正しました</p>
<p>[2016/03/08] 記録更新内容のツイート機能を追加しました</p>
<p>[2016/03/07] S乱Lv1、Lv2の曲を正しく取得できていなかった問題を修正しました</p>
<p>[2016/03/06] スパランドットコム 開設</p>

<h2 class="page-header">免責事項</h2>
<p>当サイトは、利用者に通知することなく，本サービスの内容を変更または本サービスの提供を中止することができるものとします。</p>
<p>サーバーの不具合による本サービスのデータ破損、または管理者の意図によるデータの変更に関して、一切の保証を行いません。</p>
<p>以下の行為を行った利用者に関して、管理者は事前の通知、承諾なしにデータの変更またはアカウントを停止することができるものとします。</p>
<ul>
    <li>・他のプレイヤーに成りすます行為</li>
    <li>・意図的に虚偽のデータを登録してランキングを荒らす行為</li>
    <li>・プロフィールに公序良俗に反する内容を記述する行為</li>
    <li>・その他管理者が不適切と判断する行為</li>
</ul>
<p>当サイト及び、外部リンク先のサイトを利用したことにより発生した、いかなる損失・損害についても当サイトは一切の責任と義務を負いません。</p>

<h2 class="page-header">お問い合わせ</h2>
<p>当サイトに関するお問い合わせは以下の連絡先までお願い致します。</p>
<p>ご意見、ご要望等ございましたらお気軽にご連絡ください。m(_ _)m</p>
<br>
<p>Twitter: <a href="https://twitter.com/sapuri_tappuri" target="_blank">@sapuri_tappuri</a></p>
<p>E-mail: <a href="mailto:info@srandom.com">info@srandom.com</a></p>
{% endblock %}